const express=require('express');const db=require('../db');
const {dangNhap,coMaQuyenNay,duocThaoTacDonVi}=require('../middleware/quyen');
const r=express.Router();r.use(dangNhap);
function device(id){return db.prepare(`SELECT d.*,n.ma ma_nhom,n.ten ten_nhom,m.ma_model,m.ten ten_model,px.ten ten_don_vi
 FROM devices d JOIN nhom_thiet_bi n ON n.id=d.nhom_id JOIN phan_xuong px ON px.id=d.don_vi_id
 LEFT JOIN model_thiet_bi m ON m.id=d.model_id WHERE d.id=?`).get(id);}
function allowed(req,d){return d&&duocThaoTacDonVi(req.session.nguoiDung,d.don_vi_id);}
function definitions(d){return db.prepare(`SELECT * FROM technical_attribute_definitions WHERE hoat_dong=1 AND nhom_id=?
 AND (model_id IS NULL OR model_id=?) ORDER BY CASE WHEN model_id IS NULL THEN 0 ELSE 1 END,thu_tu,ten`).all(d.nhom_id,d.model_id||-1);}
function parseOptions(raw){try{const x=JSON.parse(raw||'[]');return Array.isArray(x)?x:[];}catch(_){return[];}}
function validateValue(def,value){const errors=[];if((value===null||value===undefined||value==='')&&def.bat_buoc)return ['Giá trị bắt buộc'];if(value===null||value===undefined||value==='')return [];
 if(def.kieu_du_lieu==='NUMBER'){const n=Number(value);if(!Number.isFinite(n))errors.push('Phải là số');if(def.min_value!==null&&n<def.min_value)errors.push(`Không nhỏ hơn ${def.min_value}`);if(def.max_value!==null&&n>def.max_value)errors.push(`Không lớn hơn ${def.max_value}`);}
 if(def.kieu_du_lieu==='BOOLEAN'&&![true,false,0,1,'0','1'].includes(value))errors.push('Phải là true/false');
 if(def.kieu_du_lieu==='DATE'&&!/^\d{4}-\d{2}-\d{2}$/.test(String(value)))errors.push('Ngày phải có dạng YYYY-MM-DD');
 if(def.kieu_du_lieu==='ENUM'&&!parseOptions(def.options_json).includes(value))errors.push('Giá trị không thuộc danh sách chọn');
 if(def.pattern){try{if(!new RegExp(def.pattern).test(String(value)))errors.push('Giá trị không đúng định dạng');}catch(_){errors.push('Pattern định nghĩa không hợp lệ');}}
 return errors;}
function typed(def,value){const out={text:null,number:null,boolean:null,date:null};if(value===null||value===undefined||value==='')return out;
 if(def.kieu_du_lieu==='NUMBER')out.number=Number(value);else if(def.kieu_du_lieu==='BOOLEAN')out.boolean=[true,1,'1'].includes(value)?1:0;else if(def.kieu_du_lieu==='DATE')out.date=String(value);else out.text=String(value);return out;}
function completeness(d){const defs=definitions(d);if(!defs.length)return 100;const values=db.prepare('SELECT definition_id FROM technical_attribute_values WHERE device_id=? AND COALESCE(value_text,value_number,value_boolean,value_date) IS NOT NULL').all(d.id);const set=new Set(values.map(x=>x.definition_id));return Math.round(1000*defs.filter(x=>set.has(x.id)).length/defs.length)/10;}

r.get('/definitions',coMaQuyenNay('technical_profile.view'),(req,res)=>{const where=['d.hoat_dong=1'],p=[];if(req.query.nhom_id){where.push('d.nhom_id=?');p.push(req.query.nhom_id);}res.json(db.prepare(`SELECT d.*,n.ma ma_nhom,n.ten ten_nhom,m.ma_model FROM technical_attribute_definitions d JOIN nhom_thiet_bi n ON n.id=d.nhom_id LEFT JOIN model_thiet_bi m ON m.id=d.model_id WHERE ${where.join(' AND ')} ORDER BY n.ma,d.thu_tu`).all(...p));});
r.post('/definitions',coMaQuyenNay('technical_profile.define'),(req,res)=>{const b=req.body||{},types=['TEXT','NUMBER','BOOLEAN','DATE','ENUM'];if(!b.nhom_id||!b.ma_thuoc_tinh?.trim()||!b.ten?.trim()||!types.includes(b.kieu_du_lieu||'TEXT'))return res.status(400).json({loi:'Định nghĩa thuộc tính không hợp lệ'});if(b.min_value!==undefined&&b.max_value!==undefined&&Number(b.min_value)>Number(b.max_value))return res.status(400).json({loi:'Min không được lớn hơn max'});if(b.pattern){try{new RegExp(b.pattern);}catch(_){return res.status(400).json({loi:'Pattern không hợp lệ'});}}
 try{const info=db.prepare(`INSERT INTO technical_attribute_definitions(nhom_id,model_id,ma_thuoc_tinh,ten,kieu_du_lieu,don_vi,options_json,min_value,max_value,pattern,bat_buoc,thu_tu,nguoi_tao_id)
 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b.nhom_id,b.model_id||null,b.ma_thuoc_tinh.trim().toUpperCase(),b.ten.trim(),b.kieu_du_lieu||'TEXT',b.don_vi||null,b.options?JSON.stringify(b.options):null,b.min_value??null,b.max_value??null,b.pattern||null,b.bat_buoc?1:0,Number(b.thu_tu)||0,req.session.nguoiDung.id);res.status(201).json({id:info.lastInsertRowid,version:1});}catch(e){res.status(/UNIQUE/.test(e.message)?409:500).json({loi:/UNIQUE/.test(e.message)?'Mã thuộc tính đã tồn tại':e.message});}});
r.put('/definitions/:id',coMaQuyenNay('technical_profile.define'),(req,res)=>{const old=db.prepare('SELECT * FROM technical_attribute_definitions WHERE id=? AND hoat_dong=1').get(req.params.id);if(!old)return res.status(404).json({loi:'Không tìm thấy định nghĩa'});const b={...old,...(req.body||{})};if(b.min_value!==null&&b.max_value!==null&&Number(b.min_value)>Number(b.max_value))return res.status(400).json({loi:'Min không được lớn hơn max'});if(b.pattern){try{new RegExp(b.pattern);}catch(_){return res.status(400).json({loi:'Pattern không hợp lệ'});}}const expected=Number(req.body?.version??old.version);const result=db.prepare(`UPDATE technical_attribute_definitions SET ten=?,don_vi=?,options_json=?,min_value=?,max_value=?,pattern=?,bat_buoc=?,thu_tu=?,version=version+1,nguoi_sua_id=?,ngay_sua=datetime('now','localtime') WHERE id=? AND version=?`).run(b.ten,b.don_vi||null,b.options?JSON.stringify(b.options):b.options_json,b.min_value??null,b.max_value??null,b.pattern||null,b.bat_buoc?1:0,Number(b.thu_tu)||0,req.session.nguoiDung.id,old.id,expected);if(!result.changes)return res.status(409).json({loi:'Định nghĩa đã thay đổi'});res.json({ok:true,version:expected+1});});

r.get('/devices/:id',coMaQuyenNay('technical_profile.view'),(req,res)=>{const d=device(req.params.id);if(!d||!d.hoat_dong)return res.status(404).json({loi:'Không tìm thấy Device'});if(!allowed(req,d))return res.status(403).json({loi:'Không có quyền'});const state=db.prepare('SELECT * FROM technical_profile_state WHERE device_id=?').get(d.id)||{device_id:d.id,version:1,completeness_percent:0};const defs=definitions(d),vals=db.prepare('SELECT * FROM technical_attribute_values WHERE device_id=?').all(d.id),map=new Map(vals.map(x=>[x.definition_id,x]));const attrs=defs.map(x=>({...x,gia_tri:map.get(x.id)?.value_number??map.get(x.id)?.value_boolean??map.get(x.id)?.value_date??map.get(x.id)?.value_text??null,value_version:map.get(x.id)?.version||0,note:map.get(x.id)?.note||null}));const legacy=d.legacy_thiet_bi_id;
 res.json({overview:{...d,profile_version:state.version,completeness_percent:state.completeness_percent},attributes:attrs,
  assets:db.prepare(`SELECT a.id,a.ma_tai_san,a.ten,l.loai_quan_he,l.la_lien_ket_chinh FROM asset_device_links l JOIN assets a ON a.id=l.asset_id WHERE l.device_id=? AND l.den_ngay IS NULL`).all(d.id),
  components:db.prepare('SELECT * FROM device_components WHERE device_id=? AND active=1 ORDER BY sort_order,id').all(d.id),
  documents:legacy?db.prepare('SELECT * FROM tai_lieu_ky_thuat WHERE thiet_bi_id=? AND hoat_dong=1 ORDER BY ngay_tai DESC').all(legacy):[],
  maintenance:legacy?db.prepare('SELECT id,so_phieu,loai,trang_thai,ngay_bat_dau,ngay_hoan_thanh,tong_chi_phi FROM phieu_sua_chua WHERE thiet_bi_id=? ORDER BY ngay_tao DESC LIMIT 50').all(legacy):[],
  inspections:legacy?db.prepare('SELECT * FROM kiem_dinh WHERE thiet_bi_id=? ORDER BY ngay_kiem_dinh DESC LIMIT 50').all(legacy):[],
  history:db.prepare('SELECT * FROM technical_profile_history WHERE device_id=? ORDER BY profile_version DESC LIMIT 50').all(d.id),legacy:legacy?{bang:'thiet_bi',id:legacy}:null});});

r.put('/devices/:id/attributes',coMaQuyenNay('technical_profile.edit'),(req,res)=>{const d=device(req.params.id);if(!d||!d.hoat_dong)return res.status(404).json({loi:'Không tìm thấy Device'});if(!allowed(req,d))return res.status(403).json({loi:'Không có quyền'});const b=req.body||{},items=Array.isArray(b.values)?b.values:[],defs=definitions(d),byId=new Map(defs.map(x=>[Number(x.id),x])),errors=[];items.forEach((x,i)=>{const def=byId.get(Number(x.definition_id));if(!def)errors.push(`Dòng ${i+1}: thuộc tính không áp dụng`);else validateValue(def,x.value).forEach(e=>errors.push(`${def.ten}: ${e}`));});if(b.complete){const supplied=new Map(items.map(x=>[Number(x.definition_id),x.value]));defs.filter(x=>x.bat_buoc).forEach(def=>{const old=db.prepare('SELECT COALESCE(value_text,value_number,value_boolean,value_date) value FROM technical_attribute_values WHERE device_id=? AND definition_id=?').get(d.id,def.id);if(!supplied.has(def.id)&&old?.value==null)errors.push(`${def.ten}: Giá trị bắt buộc`);});}if(errors.length)return res.status(422).json({loi:'Dữ liệu kỹ thuật chưa hợp lệ',chi_tiet:errors});
 const state=db.prepare('SELECT * FROM technical_profile_state WHERE device_id=?').get(d.id)||{version:1};const expected=Number(b.version??state.version);if(expected!==Number(state.version))return res.status(409).json({loi:'Hồ sơ đã thay đổi; vui lòng tải lại'});try{let next;db.transaction(()=>{db.prepare('INSERT OR IGNORE INTO technical_profile_state(device_id) VALUES (?)').run(d.id);const upsert=db.prepare(`INSERT INTO technical_attribute_values(device_id,definition_id,value_text,value_number,value_boolean,value_date,note,updated_by) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(device_id,definition_id) DO UPDATE SET value_text=excluded.value_text,value_number=excluded.value_number,value_boolean=excluded.value_boolean,value_date=excluded.value_date,note=excluded.note,version=version+1,updated_by=excluded.updated_by,updated_at=datetime('now','localtime')`);const changes=[];items.forEach(x=>{const def=byId.get(Number(x.definition_id)),v=typed(def,x.value);upsert.run(d.id,def.id,v.text,v.number,v.boolean,v.date,x.note||null,req.session.nguoiDung.id);changes.push({definition_id:def.id,ma:def.ma_thuoc_tinh,value:x.value});});next=expected+1;const pct=completeness(d);const changed=db.prepare("UPDATE technical_profile_state SET version=version+1,completeness_percent=?,updated_by=?,updated_at=datetime('now','localtime') WHERE device_id=? AND version=?").run(pct,req.session.nguoiDung.id,d.id,expected);if(!changed.changes)throw Object.assign(new Error('Hồ sơ đã thay đổi; vui lòng tải lại'),{status:409});db.prepare('INSERT INTO technical_profile_history(device_id,profile_version,changes_json,changed_by) VALUES (?,?,?,?)').run(d.id,next,JSON.stringify(changes),req.session.nguoiDung.id);})();res.json({ok:true,version:next,completeness_percent:completeness(d)});}catch(e){res.status(e.status||500).json({loi:e.message});}});

module.exports=r;
