-- TASK 11: canonical warehouses and append-only stock ledger.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS warehouses(id INTEGER PRIMARY KEY AUTOINCREMENT,warehouse_code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,don_vi_id INTEGER REFERENCES phan_xuong(id),location TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','ARCHIVED')),version INTEGER NOT NULL DEFAULT 1,created_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')));
INSERT OR IGNORE INTO warehouses(warehouse_code,name,location) VALUES('LEGACY-MAIN','Kho legacy mặc định','Backfill từ kho_vat_tu');
CREATE TABLE IF NOT EXISTS stock_transactions(id TEXT PRIMARY KEY,transaction_code TEXT NOT NULL UNIQUE,type TEXT NOT NULL CHECK(type IN('RECEIPT','ISSUE','ADJUSTMENT','RESERVE','RELEASE','INCOMING','RECEIVE_INCOMING','REVERSAL')),status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','POSTED','REVERSED')),idempotency_key TEXT UNIQUE,reference_no TEXT,reason TEXT,reversal_of_id TEXT REFERENCES stock_transactions(id),created_by INTEGER REFERENCES nguoi_dung(id),posted_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),posted_at TEXT);
CREATE TABLE IF NOT EXISTS stock_transaction_lines(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES stock_transactions(id) ON DELETE CASCADE,warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),material_id INTEGER NOT NULL REFERENCES materials(id),uom_code TEXT NOT NULL REFERENCES uoms(code),quantity REAL NOT NULL CHECK(quantity>0),on_hand_delta REAL NOT NULL DEFAULT 0,reserved_delta REAL NOT NULL DEFAULT 0,incoming_delta REAL NOT NULL DEFAULT 0,note TEXT);
CREATE TABLE IF NOT EXISTS stock_ledger_entries(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES stock_transactions(id) ON DELETE RESTRICT,line_id TEXT NOT NULL REFERENCES stock_transaction_lines(id) ON DELETE RESTRICT,warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),material_id INTEGER NOT NULL REFERENCES materials(id),uom_code TEXT NOT NULL REFERENCES uoms(code),on_hand_delta REAL NOT NULL DEFAULT 0,reserved_delta REAL NOT NULL DEFAULT 0,incoming_delta REAL NOT NULL DEFAULT 0,entry_type TEXT NOT NULL,event_time TEXT NOT NULL,posted_by INTEGER REFERENCES nguoi_dung(id),reversal_of_entry_id TEXT UNIQUE REFERENCES stock_ledger_entries(id),CHECK(on_hand_delta<>0 OR reserved_delta<>0 OR incoming_delta<>0));
CREATE INDEX IF NOT EXISTS idx_stock_ledger_projection ON stock_ledger_entries(warehouse_id,material_id,uom_code);
CREATE TABLE IF NOT EXISTS stock_balance_projection(warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),material_id INTEGER NOT NULL REFERENCES materials(id),uom_code TEXT NOT NULL REFERENCES uoms(code),on_hand REAL NOT NULL DEFAULT 0,reserved REAL NOT NULL DEFAULT 0,incoming REAL NOT NULL DEFAULT 0,last_entry_id TEXT REFERENCES stock_ledger_entries(id),updated_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),PRIMARY KEY(warehouse_id,material_id,uom_code),CHECK(on_hand>=0),CHECK(reserved>=0),CHECK(incoming>=0),CHECK(reserved<=on_hand));
CREATE VIEW IF NOT EXISTS v_stock_balance AS SELECT p.*,p.on_hand-p.reserved available,w.warehouse_code,w.name warehouse_name,m.material_code,m.name material_name FROM stock_balance_projection p JOIN warehouses w ON w.id=p.warehouse_id JOIN materials m ON m.id=p.material_id;
CREATE TRIGGER IF NOT EXISTS trg_stock_entries_no_update BEFORE UPDATE ON stock_ledger_entries BEGIN SELECT RAISE(ABORT,'Stock ledger is append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_stock_entries_no_delete BEFORE DELETE ON stock_ledger_entries BEGIN SELECT RAISE(ABORT,'Stock ledger is append-only'); END;
INSERT OR IGNORE INTO stock_transactions(id,transaction_code,type,status,idempotency_key,reference_no,reason,posted_at) VALUES('stock-opening-legacy','STK-OPENING-LEGACY','ADJUSTMENT','POSTED','migration-24-opening','LEGACY','Opening balance from ton_kho',datetime('now','localtime'));
INSERT OR IGNORE INTO stock_transaction_lines(id,transaction_id,warehouse_id,material_id,uom_code,quantity,on_hand_delta,note)
SELECT 'stock-opening-line-'||k.id,'stock-opening-legacy',w.id,s.material_id,m.base_uom_code,MAX(COALESCE(t.ton_hien_tai,0),0),MAX(COALESCE(t.ton_hien_tai,0),0),'Legacy warehouse material '||k.id FROM kho_vat_tu k JOIN material_source_mappings s ON s.source_type='WAREHOUSE' AND s.source_id=CAST(k.id AS TEXT) JOIN materials m ON m.id=s.material_id CROSS JOIN warehouses w LEFT JOIN ton_kho t ON t.vat_tu_id=k.id WHERE COALESCE(t.ton_hien_tai,0)>0 AND w.warehouse_code='LEGACY-MAIN';
INSERT OR IGNORE INTO stock_ledger_entries(id,transaction_id,line_id,warehouse_id,material_id,uom_code,on_hand_delta,entry_type,event_time)
SELECT replace(id,'stock-opening-line-','stock-opening-entry-'),transaction_id,id,warehouse_id,material_id,uom_code,on_hand_delta,'OPENING',datetime('now','localtime') FROM stock_transaction_lines WHERE transaction_id='stock-opening-legacy';
INSERT OR REPLACE INTO stock_balance_projection(warehouse_id,material_id,uom_code,on_hand,reserved,incoming,last_entry_id,updated_at) SELECT warehouse_id,material_id,uom_code,SUM(on_hand_delta),SUM(reserved_delta),SUM(incoming_delta),MAX(id),datetime('now','localtime') FROM stock_ledger_entries GROUP BY warehouse_id,material_id,uom_code;
INSERT OR IGNORE INTO ma_quyen(ma,ten,mo_ta,hang_muc) VALUES('stock.view','Xem Stock Ledger','Xem kho, projection và ledger','stock'),('stock.create','Lập giao dịch kho','Tạo draft canonical','stock'),('stock.post','Post giao dịch kho','Post ledger nguyên tử','stock'),('stock.reverse','Đảo giao dịch kho','Tạo reversal append-only','stock');
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT vai_tro.id,q.ma,NULL FROM vai_tro CROSS JOIN ma_quyen q WHERE vai_tro.ma IN('admin','cd_cty') AND q.hang_muc='stock';
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT vai_tro.id,q.ma,NULL FROM vai_tro CROSS JOIN ma_quyen q WHERE vai_tro.ma IN('px','xem') AND q.ma='stock.view';
