-- TASK 12: warehouse transfer in-transit, receive and return workflow.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS warehouse_transfers(id TEXT PRIMARY KEY,transfer_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','DISPATCHED','RECEIVED','RETURNED','CANCELLED')),source_warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),destination_warehouse_id INTEGER NOT NULL REFERENCES warehouses(id),idempotency_key TEXT NOT NULL UNIQUE,reference_no TEXT,reason TEXT,version INTEGER NOT NULL DEFAULT 1,dispatch_transaction_id TEXT UNIQUE REFERENCES stock_transactions(id),receive_transaction_id TEXT UNIQUE REFERENCES stock_transactions(id),return_transaction_id TEXT UNIQUE REFERENCES stock_transactions(id),created_by INTEGER REFERENCES nguoi_dung(id),dispatched_by INTEGER REFERENCES nguoi_dung(id),received_by INTEGER REFERENCES nguoi_dung(id),returned_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),dispatched_at TEXT,received_at TEXT,returned_at TEXT,CHECK(source_warehouse_id<>destination_warehouse_id));
CREATE TABLE IF NOT EXISTS warehouse_transfer_lines(id TEXT PRIMARY KEY,transfer_id TEXT NOT NULL REFERENCES warehouse_transfers(id) ON DELETE CASCADE,material_id INTEGER NOT NULL REFERENCES materials(id),uom_code TEXT NOT NULL REFERENCES uoms(code),quantity REAL NOT NULL CHECK(quantity>0),note TEXT,UNIQUE(transfer_id,material_id,uom_code));
CREATE TABLE IF NOT EXISTS warehouse_transfer_timeline(id TEXT PRIMARY KEY,transfer_id TEXT NOT NULL REFERENCES warehouse_transfers(id) ON DELETE RESTRICT,event_type TEXT NOT NULL,from_status TEXT,to_status TEXT NOT NULL,actor_id INTEGER REFERENCES nguoi_dung(id),reason TEXT,stock_transaction_id TEXT REFERENCES stock_transactions(id),event_time TEXT NOT NULL DEFAULT(datetime('now','localtime')));
CREATE INDEX IF NOT EXISTS idx_warehouse_transfers_status ON warehouse_transfers(status,created_at);
CREATE INDEX IF NOT EXISTS idx_warehouse_transfer_timeline ON warehouse_transfer_timeline(transfer_id,event_time);
CREATE TRIGGER IF NOT EXISTS trg_warehouse_transfer_timeline_no_update BEFORE UPDATE ON warehouse_transfer_timeline BEGIN SELECT RAISE(ABORT,'Warehouse transfer timeline is append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_warehouse_transfer_timeline_no_delete BEFORE DELETE ON warehouse_transfer_timeline BEGIN SELECT RAISE(ABORT,'Warehouse transfer timeline is append-only'); END;
INSERT OR IGNORE INTO ma_quyen(ma,ten,mo_ta,hang_muc) VALUES('warehouse_transfer.view','Xem chuyển kho','Xem workflow chuyển kho','warehouse_transfer'),('warehouse_transfer.create','Lập chuyển kho','Tạo phiếu chuyển kho','warehouse_transfer'),('warehouse_transfer.dispatch','Xuất chuyển kho','Dispatch và post in-transit','warehouse_transfer'),('warehouse_transfer.receive','Nhận chuyển kho','Nhận tại kho đích','warehouse_transfer'),('warehouse_transfer.return','Hoàn trả chuyển kho','Hoàn hàng in-transit về nguồn','warehouse_transfer');
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT vai_tro.id,q.ma,NULL FROM vai_tro CROSS JOIN ma_quyen q WHERE vai_tro.ma IN('admin','cd_cty') AND q.hang_muc='warehouse_transfer';
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT vai_tro.id,q.ma,NULL FROM vai_tro CROSS JOIN ma_quyen q WHERE vai_tro.ma='px' AND q.hang_muc='warehouse_transfer';
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT vai_tro.id,q.ma,NULL FROM vai_tro CROSS JOIN ma_quyen q WHERE vai_tro.ma='xem' AND q.ma='warehouse_transfer.view';
