-- TASK 13: canonical NCVT periods, PX submissions and Material-linked lines.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS ncvt_periods(id TEXT PRIMARY KEY,period_code TEXT NOT NULL UNIQUE,year INTEGER NOT NULL CHECK(year BETWEEN 2000 AND 2200),quarter INTEGER NOT NULL CHECK(quarter BETWEEN 1 AND 4),name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','OPEN','LOCKED','CANCELLED')),version INTEGER NOT NULL DEFAULT 1,submission_deadline TEXT,note TEXT,created_by INTEGER REFERENCES nguoi_dung(id),opened_by INTEGER REFERENCES nguoi_dung(id),locked_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),opened_at TEXT,locked_at TEXT,UNIQUE(year,quarter));
CREATE TABLE IF NOT EXISTS ncvt_period_legacy_map(legacy_period_id INTEGER PRIMARY KEY REFERENCES ncvt_ky(id) ON DELETE RESTRICT,period_id TEXT NOT NULL REFERENCES ncvt_periods(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS ncvt_submissions(id TEXT PRIMARY KEY,submission_code TEXT NOT NULL UNIQUE,period_id TEXT NOT NULL REFERENCES ncvt_periods(id) ON DELETE RESTRICT,don_vi_id INTEGER NOT NULL REFERENCES phan_xuong(id) ON DELETE RESTRICT,status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','SUBMITTED','RETURNED','REJECTED','APPROVED','CANCELLED')),version INTEGER NOT NULL DEFAULT 1,idempotency_key TEXT UNIQUE,source_legacy_period_id INTEGER REFERENCES ncvt_ky(id),note TEXT,created_by INTEGER REFERENCES nguoi_dung(id),submitted_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),updated_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),submitted_at TEXT,UNIQUE(period_id,don_vi_id));
CREATE TABLE IF NOT EXISTS ncvt_submission_lines(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL REFERENCES ncvt_submissions(id) ON DELETE CASCADE,material_id INTEGER NOT NULL REFERENCES materials(id) ON DELETE RESTRICT,uom_code TEXT NOT NULL REFERENCES uoms(code),requested_quantity REAL NOT NULL CHECK(requested_quantity>0),project_name TEXT,justification TEXT,note TEXT,version INTEGER NOT NULL DEFAULT 1,source_legacy_line_id INTEGER UNIQUE REFERENCES ncvt_chi_tiet(id),created_by INTEGER REFERENCES nguoi_dung(id),created_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),updated_at TEXT NOT NULL DEFAULT(datetime('now','localtime')));
CREATE INDEX IF NOT EXISTS idx_ncvt_submissions_period ON ncvt_submissions(period_id,status,don_vi_id);
CREATE INDEX IF NOT EXISTS idx_ncvt_submission_lines ON ncvt_submission_lines(submission_id,material_id);
CREATE TABLE IF NOT EXISTS ncvt_submission_events(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL REFERENCES ncvt_submissions(id) ON DELETE RESTRICT,event_type TEXT NOT NULL,from_status TEXT,to_status TEXT NOT NULL,actor_id INTEGER REFERENCES nguoi_dung(id),reason TEXT,payload_json TEXT,event_time TEXT NOT NULL DEFAULT(datetime('now','localtime')));
CREATE TRIGGER IF NOT EXISTS trg_ncvt_submission_events_no_update BEFORE UPDATE ON ncvt_submission_events BEGIN SELECT RAISE(ABORT,'NCVT submission event is append-only'); END;
CREATE TRIGGER IF NOT EXISTS trg_ncvt_submission_events_no_delete BEFORE DELETE ON ncvt_submission_events BEGIN SELECT RAISE(ABORT,'NCVT submission event is append-only'); END;
INSERT OR IGNORE INTO ncvt_periods(id,period_code,year,quarter,name,status,note)
SELECT 'NCVT-P-'||nam||'-Q'||quy,'NCVT-'||nam||'-Q'||quy,nam,quy,'NCVT Quý '||quy||'/'||nam,'DRAFT','Backfill từ ncvt_ky; cần mở kỳ canonical trước khi PX submit' FROM ncvt_ky GROUP BY nam,quy;
INSERT OR IGNORE INTO ncvt_period_legacy_map(legacy_period_id,period_id) SELECT k.id,p.id FROM ncvt_ky k JOIN ncvt_periods p ON p.year=k.nam AND p.quarter=k.quy;
INSERT OR IGNORE INTO ncvt_submissions(id,submission_code,period_id,don_vi_id,source_legacy_period_id,note)
SELECT 'NCVT-SUB-LEGACY-'||k.id,'NCVT-SUB-LEGACY-'||k.id,p.id,k.phan_xuong_id,k.id,'Backfill draft từ kỳ legacy' FROM ncvt_ky k JOIN ncvt_periods p ON p.year=k.nam AND p.quarter=k.quy WHERE k.phan_xuong_id IS NOT NULL;
INSERT OR IGNORE INTO ncvt_submissions(id,submission_code,period_id,don_vi_id,source_legacy_period_id,note)
SELECT 'NCVT-SUB-PX-'||p.id||'-'||COALESCE(c.phan_xuong_id,k.phan_xuong_id),'NCVT-SUB-'||p.period_code||'-PX-'||COALESCE(c.phan_xuong_id,k.phan_xuong_id),p.id,COALESCE(c.phan_xuong_id,k.phan_xuong_id),MIN(k.id),'Backfill draft từ dòng NCVT legacy' FROM ncvt_chi_tiet c JOIN ncvt_ky k ON k.id=c.ky_id JOIN ncvt_periods p ON p.year=k.nam AND p.quarter=k.quy WHERE COALESCE(c.phan_xuong_id,k.phan_xuong_id) IS NOT NULL GROUP BY p.id,COALESCE(c.phan_xuong_id,k.phan_xuong_id);
INSERT OR IGNORE INTO ncvt_submission_lines(id,submission_id,material_id,uom_code,requested_quantity,project_name,justification,note,source_legacy_line_id)
SELECT 'NCVT-LINE-LEGACY-'||c.id,s.id,ms.material_id,m.base_uom_code,c.so_luong_kh,c.cong_trinh,'Backfill legacy',c.ghi_chu,c.id FROM ncvt_chi_tiet c JOIN ncvt_ky k ON k.id=c.ky_id JOIN ncvt_periods p ON p.year=k.nam AND p.quarter=k.quy JOIN ncvt_submissions s ON s.period_id=p.id AND s.don_vi_id=COALESCE(c.phan_xuong_id,k.phan_xuong_id) JOIN material_source_mappings ms ON ms.source_type='NCVT_LINE' AND ms.source_id=CAST(c.id AS TEXT) JOIN materials m ON m.id=ms.material_id WHERE c.hoat_dong=1 AND c.so_luong_kh>0;
INSERT OR IGNORE INTO ma_quyen(ma,ten,mo_ta,hang_muc) VALUES('ncvt.period.view','Xem kỳ NCVT canonical','Xem kỳ năm/quý','ncvt_canonical'),('ncvt.period.manage','Quản lý kỳ NCVT canonical','Tạo, mở và khóa kỳ','ncvt_canonical'),('ncvt.submission.view','Xem submission NCVT','Xem nhu cầu theo scope PX','ncvt_canonical'),('ncvt.submission.edit','Lập submission NCVT','Tạo và sửa draft theo Material ID','ncvt_canonical'),('ncvt.submission.submit','Trình submission NCVT','Khóa draft và trình Công ty','ncvt_canonical');
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT v.id,q.ma,NULL FROM vai_tro v CROSS JOIN ma_quyen q WHERE v.ma IN('admin','cd_cty') AND q.hang_muc='ncvt_canonical';
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT v.id,q.ma,NULL FROM vai_tro v CROSS JOIN ma_quyen q WHERE v.ma='px' AND q.ma IN('ncvt.period.view','ncvt.submission.view','ncvt.submission.edit','ncvt.submission.submit');
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT v.id,q.ma,NULL FROM vai_tro v CROSS JOIN ma_quyen q WHERE v.ma='xem' AND q.ma IN('ncvt.period.view','ncvt.submission.view');
