-- TASK 14: NCVT reviewer assignments and immutable review decisions.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS ncvt_review_assignments(id TEXT PRIMARY KEY,period_id TEXT NOT NULL REFERENCES ncvt_periods(id) ON DELETE RESTRICT,don_vi_id INTEGER NOT NULL REFERENCES phan_xuong(id) ON DELETE RESTRICT,reviewer_user_id INTEGER NOT NULL REFERENCES nguoi_dung(id) ON DELETE RESTRICT,status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','REVOKED')),version INTEGER NOT NULL DEFAULT 1,assigned_by INTEGER NOT NULL REFERENCES nguoi_dung(id),assigned_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),revoked_by INTEGER REFERENCES nguoi_dung(id),revoked_at TEXT,note TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ncvt_review_assignment_active ON ncvt_review_assignments(period_id,don_vi_id) WHERE status='ACTIVE';
CREATE INDEX IF NOT EXISTS idx_ncvt_review_assignment_user ON ncvt_review_assignments(reviewer_user_id,status);
CREATE TABLE IF NOT EXISTS ncvt_review_decisions(id TEXT PRIMARY KEY,submission_id TEXT NOT NULL REFERENCES ncvt_submissions(id) ON DELETE RESTRICT,assignment_id TEXT NOT NULL REFERENCES ncvt_review_assignments(id) ON DELETE RESTRICT,submission_version INTEGER NOT NULL,decision TEXT NOT NULL CHECK(decision IN('RETURN','REJECT','APPROVE')),reason TEXT NOT NULL CHECK(length(trim(reason))>0),decided_by INTEGER NOT NULL REFERENCES nguoi_dung(id),line_count INTEGER NOT NULL,total_requested REAL NOT NULL,snapshot_json TEXT NOT NULL,decided_at TEXT NOT NULL DEFAULT(datetime('now','localtime')),UNIQUE(submission_id,submission_version));
CREATE INDEX IF NOT EXISTS idx_ncvt_review_decisions_submission ON ncvt_review_decisions(submission_id,decided_at);
CREATE TRIGGER IF NOT EXISTS trg_ncvt_review_decisions_no_update BEFORE UPDATE ON ncvt_review_decisions BEGIN SELECT RAISE(ABORT,'NCVT review decision is immutable'); END;
CREATE TRIGGER IF NOT EXISTS trg_ncvt_review_decisions_no_delete BEFORE DELETE ON ncvt_review_decisions BEGIN SELECT RAISE(ABORT,'NCVT review decision is immutable'); END;
INSERT OR IGNORE INTO ma_quyen(ma,ten,mo_ta,hang_muc) VALUES('ncvt.review.assign','Phân công reviewer NCVT','Phân công người review theo kỳ/PX','ncvt_review'),('ncvt.review.view','Xem review NCVT','Xem assignment và quyết định','ncvt_review'),('ncvt.review.decide','Quyết định NCVT','Return, reject hoặc approve submission','ncvt_review');
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT v.id,q.ma,NULL FROM vai_tro v CROSS JOIN ma_quyen q WHERE v.ma IN('admin','cd_cty') AND q.hang_muc='ncvt_review';
INSERT OR IGNORE INTO vai_tro_quyen(vai_tro_id,ma_quyen,donvi_id) SELECT v.id,q.ma,NULL FROM vai_tro v CROSS JOIN ma_quyen q WHERE v.ma='px' AND q.ma='ncvt.review.view';
